api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ModuleViewSet
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'
router = DefaultRouter()
router.register('modules', ModuleViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth', obtain_auth_token, name='api_token_auth'),
]

itregistration/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, CourseListView, ContactFormView, ModuleRegistration, modulewithdrawl

app_name = 'itregistration'
urlpatterns = [

    path('', CourseListView.as_view(), name='home'),
    path('about', views.about, name='about'),
    path('contact', ContactFormView.as_view(), name='contact'),
    path('modules', PostListView.as_view(), name='modules'),
    path('modules/<int:pk>', PostDetailView.as_view(), name='modules_detail'),
    path('modules/new', PostCreateView.as_view(), name='modules_create'),
    path('modules/<int:pk>/update', PostUpdateView.as_view(), name='modules_update'),
    path('modules/<int:pk>/delete',PostDeleteView.as_view(), name='modules_delete'),
    path('modules/<str:username>', UserPostListView.as_view(), name='user_modules'),
    path('modules/<int:pk>/registration', ModuleRegistration, name='moduleregistration'),
    path('modules/<int:pk>/resignation', modulewithdrawl.as_view(), name='resignation')
]

mrsapp/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    

    path('register', user_views.register, name='register'),
    path('profile', user_views.profile, name='profile'),

    path('', include('itregistration.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

itregistration/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Module(models.Model):
    moduleid = models.AutoField(primary_key=True)
    modulename= models.CharField(max_length = 100, default = 'Computing')
    category = models.CharField(max_length = 100, choices = [('Cybersecurity', 'Cybersecurity'),
                ('Data Science', 'Data Science'), 
                ('Software Development', 'Software Development'), 
                ('Web Designing', 'Web Designing'), 
                ('VFX and Animation', 'VFX and Animation'), 
                ('Games Design', 'Games Design')])
    credit = models.SmallIntegerField(default = 120)
    description = models.CharField(max_length = 10000)
    available = models.BooleanField(default = True)
    author = models.ForeignKey(User, related_name = 'Module', on_delete = models.CASCADE)
    date_submitted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.modulename}, ID; {self.moduleid}.'
    
    def get_absolute_url(self):
        return reverse('itregistration:module_detail', kwargs={'pk':self.pk})
    
class Course(models.Model):
    coursename=models.CharField(max_length=100, default='Course Name')
    description=models.CharField(max_length=10000)
    modules = models.ManyToManyField(Module)

    def __str__(self):
        return f'{self.coursename}'
    
class Registration(models.Model):
    student = models.OneToOneField(User, on_delete = models.CASCADE)
    module = models.ForeignKey(Module, on_delete = models.CASCADE)
    date_of_registration = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return f'{self.student} registered to {self.module}'

itregistration/forms.py
from django import forms
from django.core.mail import send_mail
from .models import Registration

class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50)
    email = forms.EmailField()
    subject = forms.CharField(max_length = 100)
    message = forms.CharField(widget = forms.Textarea)

def send_mail(self):
    send_mail(self.cleaned_data.get('subject') + 
              ', sent on behalf of '+ 
              self.cleaned_data.get('name'), #Name
              self.cleaned_data.get('message'), #Contents
              self.cleaned_data.get('email'), #From
              ['longisland7629@gmail.com']) # Support Recipient, will not be changed in a regular circumstance, and cannot be modified outside of the code.
    ## Personal Email, functions with gmail, 
    ## might not work for other emails.

    ## You will need to change the email in ['longisland7629@gmail.com'], as this would be considered the "support email", which would be fixed.
    
class ModuleRegForm(forms.ModelForm):
    class Meta:
        model = Registration
        exclude = ['student', 'module', 'date_of_registration']

itregistration/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Module, Course, Registration
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.views.generic import View

from .forms import ContactForm, ModuleRegForm
from django.views.generic.edit import FormView
from django.contrib import messages

def superuser_required():
    def wrapper(wrapped):
        class WrappedClass(UserPassesTestMixin, wrapped):
            def test_func(self):
                return self.request.user.is_superuser

        return WrappedClass
    return wrapper
# Create your views here.

def about(request):
    return render(request, 'itregistration/about.html', {'title':'About Us'})

class ContactFormView(FormView):
    form_class = ContactForm
    template_name  = 'itregistration/contact.html'
    def get_context_data(self, **kwargs):
        context = super(ContactFormView, self).get_context_data(**kwargs)
        context.update({'title':'Contact Us'})
        return context
    
    def form_valid(self,form):
        form.send_mail()
        messages.success(self.request, 'Successfully sent the enquiry')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.warning(self.request, 'Unable to send the enquiry')
        return super().form_invalid(form)
        
    def get_success_url(self):
        return self.request.path


def modules(request):
    module = {'modules':Module.objects.all(), 'title': 'Modules'}
    return render(request, 'itregistration/modules.html', module)

class PostListView(ListView):
    model = Module
    template_name = 'itregistration/modules.html'
    context_object_name = 'modules'
    ordering = ['-date_submitted']
    paginate_by = 3

class CourseListView(ListView):
    model = Course
    template_name = 'itregistration/home.html'
    paginate_by = 3
    context_object_name = 'courses'

class UserPostListView(ListView):
    model = Module
    template_name = 'itregistration/user_modules.html'
    context_object_name = 'modules'
    paginate_by = 3

    def get_queryset(self):
        user=get_object_or_404(User, username=self.kwargs.get('username'))
        return Module.objects.filter(author=user).order_by('-date_submitted')

class PostDetailView(DetailView):
    model = Module

@superuser_required()

class PostCreateView(CreateView):
    model = Module
    fields = ['modulename', 'category', 'credit', 'description']

    def form_valid(self,form):
        form.instance.author=self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Module
    fields = ['category', 'credit', 'description']

    def test_func(self):
        module = self.get_object()
        return self.request.user == module.author
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model=Module
    success_url = '/modules'
    def test_func(self):
        module = self.get_object()
        return self.request.user == module.author

def ModuleRegistration(request,pk):
    module = get_object_or_404(Module, moduleid=pk)
    if request.method=="POST":
        form = ModuleRegForm(request.POST)
        if form.is_valid():
            reg=form.save(commit=False)
            reg.module = module
            reg.student = request.user
            reg.save()
            messages.success(request, f"You have successfully registered for the module.")
            return redirect('/modules')
        else:
            messages.warning(request, f"Something went wrong.")
            print(f"Form Errors: {form.errors}")
    else:
        form=ModuleRegForm()
    return redirect('/modules')

class modulewithdrawl(SuccessMessageMixin, DeleteView):
    model = Registration
    success_message = "You have successfully resigned from the module."
    def get_success_url(self):
        return reverse('modules')

itregistration/templates/itregistration/about.html
{% extends "itregistration/base.html" %}
{% block content %}
<h2><em>Module Registration Service: <b style="color:#5f788a;">About Us</b></em></h2>

<p>

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas porttitor consectetur nunc a volutpat. Pellentesque condimentum tellus in nisl gravida, non mattis nisl tristique. Quisque ullamcorper accumsan magna, eu euismod lorem aliquam eu. Proin imperdiet placerat orci ut feugiat. Etiam bibendum orci sed malesuada dignissim. Donec porta neque sed metus feugiat blandit. Donec elementum elit augue, et interdum ipsum lacinia vel. Curabitur vitae metus accumsan, ullamcorper dui eu, ullamcorper dolor. <br /> <br />
    
    Phasellus lacus nisi, imperdiet eu sapien vitae, mollis cursus nisi. Ut in mi risus. Quisque in ultrices purus. Quisque nunc turpis, interdum a mattis quis, faucibus et felis. Nam dapibus dui nec venenatis hendrerit. Donec imperdiet sapien at ex mollis vehicula. Morbi est nunc, tempus non purus aliquet, facilisis interdum ex. Sed eu egestas odio. Maecenas a est arcu. Pellentesque congue ipsum vel nibh accumsan, ut laoreet risus venenatis. Proin eu porttitor purus. <br /> <br />
    
    Etiam vehicula ligula eu rhoncus suscipit. Vestibulum vel leo dignissim, convallis elit in, ornare nunc. Etiam luctus blandit augue a molestie. Praesent porttitor elit turpis, eu aliquet tortor bibendum non. Integer quis dolor lectus. Quisque sit amet est et nisi porta vulputate. Curabitur id viverra est. Donec fringilla massa vel laoreet convallis. Maecenas nec libero sit amet eros rutrum fringilla quis ut ante. Maecenas ac ligula bibendum, ultrices nibh a, dapibus risus. <br /> <br />
    
    Phasellus vel augue in felis fermentum maximus sit amet id diam. Fusce lobortis, quam ut luctus lobortis, augue mauris fermentum felis, eu dapibus leo risus in sem. Vivamus consequat eleifend elit sit amet egestas. Cras efficitur lorem purus, in facilisis magna vehicula eu. Ut id ullamcorper mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec rutrum ante. Duis dictum lacus eu sapien pellentesque, vitae elementum arcu consectetur. Curabitur quis erat lectus. <br /> <br />
    
    Mauris semper diam in risus aliquet, a blandit erat ornare. Aliquam vulputate ligula leo, at mattis purus varius quis. Aenean lacinia, enim eu pellentesque rhoncus, urna purus mollis elit, euismod scelerisque ante felis sit amet arcu. Cras mollis quis nibh non tincidunt. Praesent non viverra orci. Nullam quis dolor nec dui auctor varius at pellentesque lacus. Fusce non sem dictum, interdum nunc vel, bibendum lacus. Phasellus urna tortor, faucibus vel faucibus in, iaculis ut orci. Quisque et tellus diam. </p>

{% endblock content %}

itregistration/templates/itregistration/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <title>Module Registration Services - {{title}}</title>
</head>

<body>
    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="#">Module Registration Service</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'itregistration:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'itregistration:about' %}">About</a>
                        <a class="nav-item nav-link" href="{% url 'itregistration:contact' %}">Contact</a>
                        <a class="nav-item nav-link" href="{% url 'itregistration:modules' %}">Modules</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>

                            {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>

                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock %}
        </div>
        {% block sidebar %}
        {% endblock %}
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

itregistration/templates/itregistration/contact.html
{% extends "itregistration/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1><br /> <b style="color:#5f788a;">MRS Contact Support</b></h1>

<div class = "content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Contact us.</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

itregistration/templates/itregistration/home.html
{% extends "itregistration/base.html" %}
{% block content %}
<h1>Welcome to the<br /> <b style="color:#5f788a;">Module Registration Service</b></h1>

<p>

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas porttitor consectetur nunc a volutpat. Pellentesque condimentum tellus in nisl gravida, non mattis nisl tristique. Quisque ullamcorper accumsan magna, eu euismod lorem aliquam eu. Proin imperdiet placerat orci ut feugiat. Etiam bibendum orci sed malesuada dignissim. Donec porta neque sed metus feugiat blandit. Donec elementum elit augue, et interdum ipsum lacinia vel. Curabitur vitae metus accumsan, ullamcorper dui eu, ullamcorper dolor. <br /> <br />
    
    Phasellus lacus nisi, imperdiet eu sapien vitae, mollis cursus nisi. Ut in mi risus. Quisque in ultrices purus. Quisque nunc turpis, interdum a mattis quis, faucibus et felis. Nam dapibus dui nec venenatis hendrerit. Donec imperdiet sapien at ex mollis vehicula. Morbi est nunc, tempus non purus aliquet, facilisis interdum ex. Sed eu egestas odio. Maecenas a est arcu. Pellentesque congue ipsum vel nibh accumsan, ut laoreet risus venenatis. Proin eu porttitor purus. <br /> <br />
    
    Etiam vehicula ligula eu rhoncus suscipit. Vestibulum vel leo dignissim, convallis elit in, ornare nunc. Etiam luctus blandit augue a molestie. Praesent porttitor elit turpis, eu aliquet tortor bibendum non. Integer quis dolor lectus. Quisque sit amet est et nisi porta vulputate. Curabitur id viverra est. Donec fringilla massa vel laoreet convallis. Maecenas nec libero sit amet eros rutrum fringilla quis ut ante. Maecenas ac ligula bibendum, ultrices nibh a, dapibus risus. <br /> <br />
    
    Phasellus vel augue in felis fermentum maximus sit amet id diam. Fusce lobortis, quam ut luctus lobortis, augue mauris fermentum felis, eu dapibus leo risus in sem. Vivamus consequat eleifend elit sit amet egestas. Cras efficitur lorem purus, in facilisis magna vehicula eu. Ut id ullamcorper mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec rutrum ante. Duis dictum lacus eu sapien pellentesque, vitae elementum arcu consectetur. Curabitur quis erat lectus. <br /> <br />
    
    Mauris semper diam in risus aliquet, a blandit erat ornare. Aliquam vulputate ligula leo, at mattis purus varius quis. Aenean lacinia, enim eu pellentesque rhoncus, urna purus mollis elit, euismod scelerisque ante felis sit amet arcu. Cras mollis quis nibh non tincidunt. Praesent non viverra orci. Nullam quis dolor nec dui auctor varius at pellentesque lacus. Fusce non sem dictum, interdum nunc vel, bibendum lacus. Phasellus urna tortor, faucibus vel faucibus in, iaculis ut orci. Quisque et tellus diam. </p>

{% endblock content %}

{% block sidebar %}
<div class="col-md-4">
    <div class="content-section">
        <h3>Courses</h3>
        <p class='text-muted'>Here you can see all of our available courses.
            <ul class="list-group">
                {% for course in courses %}
                    <li class="list-group-item list-group-item-light"><u>{{ course.coursename }}</u> <br /> {{ course.description|truncatechars:75 }} <br /> <u>Found in Modules;</u> <br />{% for modules in course.modules.all %}<ul>{{ modules.modulename }}</ul>{% endfor %}</li>
                {% endfor %}
            </ul>
            <br />
            {% if is_paginated %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-info mb-4"href="?page={{num}}">{{num}}</a>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-info mb-4"href="?page={{num}}">{{num}}</a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </p>
    </div>
</div>
{% endblock %}

itregistration/templates/itregistration/module_confirm_delete.html
{% extends "itregistration/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Module?</legend>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'itregistration:modules_detail' object.moduleid %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

itregistration/templates/itregistration/module_detail.html
{% extends "itregistration/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Module Registration Service</h1>

<h2 class="article-title">{{ object.modulename }} </h2>
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{object.author.profile.image.url }}"/>
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'itregistration:user_modules' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_submitted}}</small>
        </div>
        <h2>{{ object.modulename }}</h2>
        <p class="article-content">{{ object.details }}</p>
        {% if object.author == user or user.is_superuser %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'itregistration:modules_update' object.moduleid %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'itregistration:modules_delete' object.moduleid %}">Delete</a>
        {% endif %}

        {% if user.is_authenticated %}  

            {% if module.available == True %}
                <form method="POST" action = "{% url 'itregistration:moduleregistration' module.moduleid %}">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-success" type="submit">Register Now</button>
                </form>

                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'itregistration:resignation' module.moduleid %}">Resign</a>
            {% else %}
                <a class="mr-2">This course is unavailable.</a>
            {% endif %}
        
        {% else %}
            <a class="mr-2">You cannot register for a module without an account.</a>
            <a class="ml-2" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</article>

{% endblock content %}

itregistration/templates/itregistration/module_form.html
{% extends "itregistration/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Staff Module Creation Form</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
    </form>
</div>
{% endblock content %}

itregistration/templates/itregistration/modules.html
{% extends "itregistration/base.html" %}
{% block content %}
<h1>Module Registration Service</h1>

{% if request.user.is_superuser %}
<article class="media content-section">
    <div>
        <p class="article-content">Hello, {{ user.username }}, would you like to create a module?</p>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'itregistration:modules_create' %}">Create Module</a>
    </div>
</article>
{% endif %}

{% for module in modules %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ module.author.profile.image.url }}" />
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'itregistration:user_modules' module.author.username %}">{{ module.author.username }}</a>
            <small class="text-muted">{{ module.date_submitted}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'itregistration:modules_detail' module.moduleid %}">{{ module.modulename }}</a></h2>
        <p class="article-content">{{ module.description }}</p>
    </div>
</article>
{% endfor %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4"href="?page={{num}}">{{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4"href="?page={{num}}">{{num}}</a>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
    {% endif %}
{% endif %}

{% endblock content %}

itregistration/templates/itregistration/registration_confirm_delete.html
{% extends "itregistration/base.html" %}
{% block content %}
<div class="content-section">
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <article class="media content-section">
                <div class="media-body">
                    <h2><a class="article-title">{{object.module}}</a></h2>
                    <p class="article-content">{{ object.module.credit }} credits offered.<br />Module Code: {{ object.module.code }}<br /></p>
                </div>
            </article>
        </fieldset>
        <legend class="border-bottom mb-4">Are you sure you want to delete this resignation?</legend>
        <div class="form-group">
            <button class="btn btn-outline-danger" href="{% url 'itregistration:modules' object.student %}" type="submit">Confirm Resignation</button>
            <button class="btn btn-outline-secondary" href="{% url 'itregistration:modules' %}">Cancel</button>
        </div>
    </form>
</div>
{% endblock content %}

itregistration/templates/itregistration/user_modules.html
{% extends "itregistration/base.html" %}
{% block content %}
<h1>Modules by {{ view.kwargs.username }} {% if is_paginated %}(page {{page_obj.number}} of {{page_obj.paginator.num_pages}}){% endif %}</h1>

{% for module in modules %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ module.author.profile.image.url }}" />
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2">{{ module.author.username }}</a>
            <small class="text-muted">{{ module.date_submitted}}</small>
        </div>
        <h2><a class="article-title" href="{% url 'itregistration:modules_detail' module.moduleid %}">{{ module.modulename }}</a></h2>
        <p class="article-content">{{ module.description }}</p>
    </div>
</article>
{% endfor %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4"href="?page={{num}}">{{num}}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4"href="?page={{num}}">{{num}}</a>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
    {% endif %}
{% endif %}

{% endblock content %}